### PR TITLE
Added dictionary functionality to Rule(6) class

### PR DESCRIPTION
**Pull request by jllorente**
This commit adds the dictionary functionality to Rule() and Rule6() classes.
This addresses a previous feature request reported in issue https://github.com/ldx/python-iptables/issues/219

### CODE REVIEW

**Comment by ldx** [comment]
Did you try running tests locally? They failed on Travis:

```
test_hashlimit (tests.test_matches.TestHashlimitMatch) ... 
travis_time:end:054ea712:start=1510535572443631907,finish=1510535573155267335,duration=711635428
[0K
[31;1mThe command "sudo PATH=$PATH coverage run setup.py test" exited with 139.[0m

Done. Your build exited with 1.
```

**Comment by jllorente** [comment]
I ran the test on my system for both python2 (2.7.12) and python3 (3.5.2). They ran ok, all of them :) 
```
~/python-iptables/tests# $PYTHON ./test_iptc.py
~/python-iptables/tests# $PYTHON ./test_matches.py
~/python-iptables/tests# $PYTHON ./test_targets.py
```

**Comment by ldx** [comment]
Sorry for the delay on my part, I'd like to look into the failures in the Travis CI build. They look like segfaults when running the test suite.

**Comment by jllorente** [comment]
It seems the build issues have been resolved and now there are no conflicts. I have also improved the dictionary generation function to remove empty lists and fields.

**Comment by ldx** [comment]
Nice! Can you also add tests for the dict methods, and a few lines to `doc/examples.rst`? Thanks!

**Comment by jllorente** [comment]
I completely forgot about this PR, sorry about that!
Can we merge as is ?

**Pull request merged**
