### PR TITLE
Apply subnet mask to IP address - issue260

### PR DESCRIPTION
**Pull request by jllorente**
Sanitize IP address with netmask when creating a Rule().
```
>>> import iptc
>>> rule = iptc.easy.encode_iptc_rule({'dst':'10.10.10.10/24'})
>>> rule.dst
'10.10.10.0/255.255.255.0'
```

### CODE REVIEW

**Comment by ldx** [comment]
@jllorente do you have access to e.g. https://travis-ci.org/ldx/python-iptables/jobs/534544125 to check why a build has failed?

**Comment by multun** [comment]
@ldx @jllorente that's because these tests are incorrect https://github.com/ldx/python-iptables/blob/master/tests/test_iptc.py#L623

I guess normalizing the expected answers will do the trick

**Comment by ldx** [comment]
OIC, indeed, this should be fixed in the test.

**Comment by ldx** [comment]
Can you please rebase this on master to fix the Travis CI build?

**Pull request closed without merging**
