### PR TITLE
Improve usability via iptc.easy

### PR DESCRIPTION
**Pull request by jllorente**
[do not merge]
Placeholder for addressing the issue discussed https://github.com/ldx/python-iptables/issues/268
This PR contains a first version of the ported iptc_helper developed earlier.
It adds new functionality regarding get/set policy.
It should obsolete PR https://github.com/ldx/python-iptables/pull/222 regarding the dictionary functionality, as we now expose encode../decode.. functions in this new module.

### CODE REVIEW

**Comment by ldx** [comment]
Looks good. Can you also:
- add tests for the public functions and
- update the README?

As for the README update, I think it'd be useful to add a short explanation on the use case (higher level than the current library, easier to use for short scripts) and a few simple examples?

**Comment by jllorente** [comment]
Regarding the tests, anything else than the decode() encode() functions that translate betwen iptc_rules to dictonaries would require admin rights to run, that's why I decided not to include them.
And for the README section, perhaps we could include the full list with the supported functions in the *easy* module instead?
@ldx, let me know what you think

**Comment by jllorente** [comment]
Regarding the tests, anything else than the decode() encode() functions that translate betwen iptc_rules and dictionaries would require admin rights to run, that's why I decided not to include them.
And for the README section, perhaps we could include the full list with the supported functions in the *easy* module instead?
@ldx, let me know what you think

**Comment by ldx** [comment]
@jllorente it's okay if not every function from the easy module is documented in the README, users can check out the module itself.

I think this is good to merge, anything else you'd like to add?

**Comment by jllorente** [comment]
Alright then, let's merge it at this time so people are able to start using it. Hopefully we'll get some feedback on how to improve it!

**Comment by ldx** [comment]
Thanks! I've also added you as a collaborator of the project. LMK if you have any questions.

**Pull request merged**
