### PR TITLE
Update debian files and .gitignore

### PR DESCRIPTION
**Pull request by fuhry**
* Sync debian package version to upstream version
* Add debhelper-generated files to .gitignore

### CODE REVIEW

**Comment by fuhry** [comment]
Hi @ldx! We at @datto are using your Python module for an internal project, and updated the build files for Ubuntu 16.04. We can build against my branch but as a rule we try to submit improvements back to upstream when possible.

Specifically could you let me know if you need the distro codename changed back, or other tweaks made to the control and changelog files? The `python-support` package [was removed after Ubuntu 14.04](http://packages.ubuntu.com/trusty/python-support), hence the removal of that dependency.

**Comment by ldx** [comment]
@fuhry when I try to build a package from your branch it fails with:

     dpkg-source -b python-iptables
    dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
    dpkg-buildpackage: error: dpkg-source -b python-iptables gave error exit status 255

This is on Debian 8. Seems dpkg does not like the new revision number `0.12.0-1`. Changing it to `0.12.0.1` fixes the problem for me.

**Comment by fuhry** [comment]
@ldx Sorry for the delay, but I've just fixed this and resolved the `.gitignore` conflicts. This should be ready to merge now.

**Comment by ldx** [comment]
Thanks!

**Pull request merged**
