### PR TITLE
Add code coverage tracking integrated with Coveralls.io

### PR DESCRIPTION
**Pull request by evilaliv3**
While working on [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) and evaluating python-iptables integration we found out that code coverage is currently not tracked during unit-tests.

It would be valuable to integrate the tracking of such a metric in order to prove the quality of the code, improve it by eventually founding and correcting dead branches of code.

This could be done by using coverage/coveralls and results can be exposed through the README.md file.

screenshot from 2016-01-01 16 37 10
screenshot from 2016-01-01 16 37 30

as proved by the above screenshots the current code coverage is poor (~60%) but tracking it is the first starting point for improving it.

### CODE REVIEW

**Comment by ldx** [comment]
Awesome, thanks a lot!

**Comment by evilaliv3** [comment]
:)

there are still two changes you should apply:
- the badge exposed on the README.md should be changed in order to point to the master branch.
- you should add your repository to landscape if you want the badge to show info about the code quality (that basically is an execution of pyllnt)

**Comment by ldx** [comment]
Yup, landscape is still syncing my GitHub repos. Thanks!

**Comment by ldx** [comment]
@evilaliv3 landscape is still syncing my github repos - any suggestions? I signed up for the free trial with my GH account.

2016-01-06-102442_2560x1440_scrot

**Comment by evilaliv3** [comment]
it seems that thos days it is having issues :/ 

for what relates to the coveralls badge i would suggest you to chang it to: 
[Coverage Status](https://coveralls.io/github/ldx/python-iptables?branch=master)

i think that the service=github does the trick of forging github to update the web cache

**Pull request merged**
