### PR TITLE
Proper error import & lib autodetection

### PR DESCRIPTION
**Pull request by vintozver**
Move errors out to the separate module to be able to catch the import level errors

Autodetect lib dirs and import xtables

### CODE REVIEW

**Comment by ldx** [comment]
@vintozver the tests on Travis failed, can you take a look?

**Comment by vintozver** [comment]
stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, universal_newlines=True
AttributeError: 'module' object has no attribute 'DEVNULL'

will fix now

**Comment by vintozver** [comment]
tests are not passing, sorry for the mess :)

**Comment by ldx** [comment]
Thanks!

**Pull request merged**
